name: C++ CI

on: 
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'CMakeLists.txt'
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Release]
        use_asan_and_ubsan: [ON, OFF]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            ccache

      - name: Install GCC 14
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-${{ matrix.build_type }}-${{ matrix.use_asan_and_ubsan }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.build_type }}-

      - name: Configure CMake
        run: >
          cmake -B build -G Ninja
          -DCMAKE_CXX_COMPILER=g++-14 
          -DCMAKE_C_COMPILER=gcc-14
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DENABLE_SANITIZERS=${{ matrix.use_asan_and_ubsan }}
          -DBUILD_WITH_TRACY=OFF

      - name: Build
        run: cmake --build build

      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure
